plugin:
  # Sends logs over to jq for processing. This leverages kubectl plugin kubectl-jq.
  jqlogs:
    shortCut: Ctrl-J
    confirm: false
    description: "Logs (jq)"
    scopes:
      - po
    command: kubectl-jq
    background: false
    args:
      - $NAME
      - $NAMESPACE
      - $CONTEXT
