format = """
[┌───────────────────>](bold green)
[│](bold green)$directory$git_branch$git_status
[└─>](bold green)"""

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
style = "yellow"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
style = "green"
symbol = ""

[git_status]
style = "bold red"
