format = """
[┌───────────────────>](bold green)
[│](bold green)$directory$git_branch$git_status
[└─>](bold green) """

# Disable the blank line at the start of the prompt
add_newline = false

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[directory]
style = "yellow"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
style = "green"
symbol = ""

[git_status]
style = "bold red"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
